name:                algebraic
version:             0.1.0.0
github:              "githubuser/algebraic"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/algebraic#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- th-compat
- containers
- deepseq
- criterion
- ghc-prof
- array
- mtl
- QuickCheck
- generic-random

default-extensions:
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- DeriveFunctor
- DeriveGeneric
- DerivingVia
- UndecidableInstances
- ScopedTypeVariables

other-extensions:
- TemplateHaskell

library:
  source-dirs: src

executables:
  algebraic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - algebraic
  algebraic-benchmark:
    main:                Main.hs
    source-dirs:         benchmarks
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    - -fspecialise-aggressively
    - -fforce-recomp
    # - -fno-full-laziness 
    # ^ http://www.serpentine.com/criterion/tutorial.html#beware-pretend-io
    dependencies:
    - algebraic
  algebraic-profile:
    main:                Main.hs
    source-dirs:         profiling
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    - -fspecialise-aggressively
    dependencies:
    - algebraic
  algebraic-core:
    main:                Main.hs
    source-dirs:         profiling
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    - -ddump-to-file
    - -fspecialise-aggressively
    - -fexpose-all-unfoldings
    # 
    - -fdicts-cheap
    - -funfolding-dict-discount=1000
    # 
    # - -dsuppress-coercions
    # - -dsuppress-module-prefixes
    # - -dsuppress-type-applications
    - -ddump-ds
    - -ddump-spec
    - -ddump-simpl
    - -fforce-recomp
    - -fplugin GhcDump.Plugin
    dependencies:
    - algebraic
    - ghc-dump-core

tests:
  algebraic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic
